# Generated by Django 5.2.6 on 2025-09-15 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("address", "0001_initial"),
        ("billing_profile", "0001_initial"),
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("paid", "Paid"),
                            ("shipped", "Shipped"),
                            ("refunded", "Refunded"),
                        ],
                        default="created",
                        max_length=120,
                    ),
                ),
                (
                    "shipping_total",
                    models.DecimalField(decimal_places=2, default=5.99, max_digits=100),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                ("active", models.BooleanField(default=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "billing_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_address",
                        to="address.address",
                    ),
                ),
                (
                    "billing_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billing_profile.billingprofile",
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cart.cart"
                    ),
                ),
                (
                    "shipping_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_address",
                        to="address.address",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp", "-updated"],
            },
        ),
    ]
