# Generated by Django 5.2.6 on 2025-09-19 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0001_initial"),
        ("billing_profile", "0001_initial"),
        ("cart", "0001_initial"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="billing_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="billing_address",
                to="address.address",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="billing_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="billing_profile.billingprofile",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="cart.cart"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="shipping_address",
                to="address.address",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated",
            field=models.DateTimeField(),
        ),
    ]
